{% set name = "pymovements" %}
{% set version = "0.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pymovements-{{ version }}.tar.gz
  sha256: b349a60578511e78faa6709963d19d50109faee1489f2e3933371e444794ba17

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base >=3.8.0,<3.10
    - numpy >=1.22.4,<3
    - pandas >2.1.4,<3
    - polars >=1.8.2,<2
    - pyarrow >=11.0.0,<19
    - pyopenssl >=16.0.0,<25.0.0
    - scipy >=1.8.0,<2
    - tqdm >=4.27.0,<5
    - typing_extensions >=4.0.0,<5

test:
  imports:
    - pymovements
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/aeye-lab/pymovements
  summary: A python package for processing eye movement data
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - dkrako
