{% set name = "pymovements" %}
{% set version = "0.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pymovements-{{ version }}.tar.gz
  sha256: 3f1cb00009ba83393daef6d0c2eec0eb06c3ea5bf81b5d3085033be0a0397a9a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base >=3.8.0,<3.9
    - numpy >=1.22.4,<2
    - pandas >2.1.4,<3
    - polars >=0.20.1,<0.20.3
    - pyarrow >=11.0.0,<16
    - pyopenssl >=16.0.0,<25.0.0
    - scipy >=1.8.0,<2
    - tqdm >=4.27.0,<5
    - typing_extensions >=4.0.0,<5

test:
  imports:
    - pymovements
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/aeye-lab/pymovements
  summary: A python package for processing eye movement data
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - dkrako
