{% set name = "pymovements" %}
{% set version = "0.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pymovements-{{ version }}.tar.gz
  sha256: 2a263a040cabe91ee25c13a543b528a52ee9d1a14b1295322755daa7531037db

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >=3.9
    - matplotlib-base >=3.8.0,<3.9
    - numpy >=1.22.4,<2
    - pandas >2.1.4,<3
    - polars >=0.20.1,<0.20.3
    - pyarrow >=11.0.0,<16
    - pyopenssl >=16.0.0,<25.0.0
    - scipy >=1.8.0,<2
    - tqdm >=4.27.0,<5
    - typing_extensions >=4.0.0,<5

test:
  imports:
    - pymovements
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aeye-lab/pymovements
  summary: A python package for processing eye movement data
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - dkrako
