{% set name = "pymovements" %}
{% set version = "0.16.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pymovements-{{ version }}.tar.gz
  sha256: 76a35b358ff2e35834b369c599c5e77e60d97040c267f3ac641558cf0cc57535

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >=3.7
    - matplotlib-base >=3.0.0
    - numpy >=1.10.0
    - pandas >1.0.0
    - polars >=0.18.3,<0.19.0
    - pyarrow >=4.0.0,<12.0.0
    - scipy >=1.5.4
    - tqdm >=4.0.0
    - typing_extensions >=4.0.0

test:
  imports:
    - pymovements
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aeye-lab/pymovements
  summary: A python package for processing eye movement data
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - dkrako
