{% set name = "pymovements" %}
{% set version = "0.24.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pymovements-{{ version }}.tar.gz
  sha256: 74b04e435b4fde21c774b87a305e19d42a0435054b69aa118248d81b5b315bce

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0.0,<81
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - deprecated >=1.2.18,<1.4
    - fastexcel >=0.13.0,<1.0
    - matplotlib-base >=3.8.0,<3.11
    - numpy >=1.22.4,<2.3
    - pandas >2.1.4,<2.4
    - polars >=1.31.0,<1.32
    - pyarrow >=11.0.0,<21.1
    - pyopenssl >=16.0.0,<25.4
    - pyreadr >=0.5.2,<0.6
    - pyyaml >=6.0.2,<6.1
    - scipy >=1.8.0,<1.16
    - tqdm >=4.27.0,<4.68
    - typing_extensions >=4.0.0,<4.16

test:
  imports:
    - pymovements
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pymovements/pymovements
  summary: A python package for processing eye movement data
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - dkrako
