{% set name = "pymovements" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pymovements-{{ version }}.tar.gz
  sha256: b0a23f394c561c4afd1e56cc8d74a36c548371fcfe2e10d50f1d20c65ffa3d7e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >=3.7
    - matplotlib-base >=3.0.0
    - numpy >=1.10.0
    - pandas >1.0.0
    - polars >=0.15.0
    - pyarrow >=4.0.0
    - scipy >=1.5.4
    - tqdm >=4.0.0

test:
  imports:
    - pymovements
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aeye-lab/pymovements
  summary: A python package for processing eye movement data
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - dkrako
