{% set name = "pymovements" %}
{% set version = "0.25.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pymovements-{{ version }}.tar.gz
  sha256: 76ab902cb65d2ef933da45a869d1422d0807d06661d36bbec589e757a48102a4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - deprecated >=1.2.18
    - fastexcel >=0.13.0
    - matplotlib-base >=3.8.0
    - numpy >=1.22.4
    - pandas >2.1.4
    - polars >=1.34.0
    - pyarrow >=11.0.0
    - pyopenssl >=22.0.0
    - pyparsing >=3.1.2
    - pyreadr >=0.5.2
    - pyyaml >=6.0.2
    - scikit-learn >=1.2
    - scipy >=1.8.0
    - tqdm >=4.63.0
    - typing_extensions >=4.0.0

test:
  imports:
    - pymovements
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pymovements/pymovements
  summary: A python package for processing eye movement data
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - dkrako
